version: "3.8"

services:
  portfolio:
    container_name: portfolio
    build: .
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      make start-dev
    networks:
      - ndprojects

networks:
  ndprojects:
    driver: bridge
