import { SkillData } from "@/@types";

export const skills: SkillData[] = [
  {
    name: "BeekeeperStudio",
    description: "BeekeeperStudio.Description",
    categories: ["Database", "Tools"],
    url: "https://www.beekeeperstudio.io/",
  },
  {
    name: "BiomeJS",
    description: "BiomeJS.Description",
    categories: ["Tools"],
    url: "https://biomejs.com/",
  },
  {
    name: "CSS3",
    description: "CSS3.Description",
    categories: ["Frontend"],
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    name: "DiscordJS",
    description: "DiscordJS.Description",
    categories: ["Library"],
    url: "https://discord.js.org/",
  },
  {
    name: "Docker",
    description: "Docker.Description",
    categories: ["DevOps", "Tools"],
    url: "https://www.docker.com/",
  },
  {
    name: "ESLint",
    description: "ESLint.Description",
    categories: ["Tools"],
    url: "https://eslint.org/",
  },
  {
    name: "GitHub",
    description: "GitHub.Description",
    categories: ["Tools"],
    url: "https://github.com/NedcloarBR",
  },
  {
    name: "HTML5",
    description: "HTML5.Description",
    categories: ["Frontend"],
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    name: "JavaScript",
    description: "JavaScript.Description",
    categories: ["Frontend", "Backend"],
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    name: "MongoDB",
    description: "MongoDB.Description",
    categories: ["Database"],
    url: "https://www.mongodb.com/",
  },
  {
    name: "Necord",
    description: "Necord.Description",
    categories: ["Library"],
    url: "https://necord.org/",
  },
  {
    name: "NestJS",
    description: "NestJS.Description",
    categories: ["Backend"],
    url: "https://nestjs.com/",
  },
  {
    name: "NextJS",
    description: "NextJS.Description",
    categories: ["Frontend", "Backend"],
    url: "https://nextjs.org/",
  },
  {
    name: "NodeJS",
    description: "NodeJS.Description",
    categories: ["Backend", "Frontend"],
    url: "https://nodejs.org/",
  },
  {
    name: "PostgreSQL",
    description: "PostgreSQL.Description",
    categories: ["Database"],
    url: "https://www.postgresql.org/",
  },
  {
    name: "Postman",
    description: "Postman.Description",
    categories: ["Tools"],
    url: "https://www.postman.com/",
  },
  {
    name: "Prisma",
    description: "Prisma.Description",
    categories: ["Database", "Tools"],
    url: "https://www.prisma.io/",
  },
  {
    name: "ReactJS",
    description: "ReactJS.Description",
    categories: ["Frontend"],
    url: "https://reactjs.org/",
  },
  {
    name: "TailwindCSS",
    description: "TailwindCSS.Description",
    categories: ["Frontend"],
    url: "https://tailwindcss.com/",
  },
  {
    name: "TypeScript",
    description: "TypeScript.Description",
    categories: ["Frontend", "Backend"],
    url: "https://www.typescriptlang.org/",
  },
  {
    name: "Vercel",
    description: "Vercel.Description",
    categories: ["DevOps", "Tools"],
    url: "https://vercel.com/",
  },
  {
    name: "Yarn",
    description: "Yarn.Description",
    categories: ["Tools"],
    url: "https://yarnpkg.com/",
  },
];
