export * from "./about";
export * from "./change-language";
export * from "./competencies"
export * from "./contact"
export * from "./footer"
export * from "./header/header"
export * from "./header/header-anchor"
export * from "./main-container"
export * from "./projects"
export * from "./start"
export * from "./theme/theme-provider"
export * from "./theme/toggle-theme"